<script>
    //<![CDATA[
    var H5PIntegration = {
        "baseUrl": "https:\/\/qmplus.qmul.ac.uk\/",
        "url": "https:\/\/qmplus.qmul.ac.uk\/pluginfile.php\/1355653\/mod_hvp",
        "urlLibraries": "https:\/\/qmplus.qmul.ac.uk\/pluginfile.php\/1\/mod_hvp\/libraries",
        "postUserStatistics": true,
        "ajax": {
            "setFinished": "https:\/\/qmplus.qmul.ac.uk\/mod\/hvp\/ajax.php?contextId=1355653&token=f0d8edb50306c&action=set_finished",
            "xAPIResult": "https:\/\/qmplus.qmul.ac.uk\/mod\/hvp\/ajax.php?contextId=1355653&token=cd2ae288b2f80&action=xapiresult",
            "contentUserData": "https:\/\/qmplus.qmul.ac.uk\/mod\/hvp\/ajax.php?contextId=1355653&token=624d8ef2fbac5&action=contents_user_data&content_id=:contentId&data_type=:dataType&sub_content_id=:subContentId"
        },
        "saveFreq": false,
        "siteUrl": "https:\/\/qmplus.qmul.ac.uk",
        "l10n": {
            "H5P": {
                "fullscreen": "Fullscreen",
                "disableFullscreen": "Disable fullscreen",
                "download": "Download",
                "copyrights": "Rights of use",
                "embed": "Embed",
                "size": "Size",
                "showAdvanced": "Show advanced",
                "hideAdvanced": "Hide advanced",
                "advancedHelp": "Include this script on your website if you want dynamic sizing of the embedded content:",
                "copyrightInformation": "Rights of use",
                "close": "Close",
                "title": "Title",
                "author": "Author",
                "year": "Year",
                "source": "Source",
                "license": "License",
                "thumbnail": "Thumbnail",
                "noCopyrights": "No copyright information available for this content.",
                "reuse": "Reuse",
                "reuseContent": "Reuse Content",
                "reuseDescription": "Reuse this content.",
                "downloadDescription": "Download this content as a H5P file.",
                "copyrightsDescription": "View copyright information for this content.",
                "embedDescription": "View the embed code for this content.",
                "h5pDescription": "Visit H5P.org to check out more cool content.",
                "contentChanged": "This content has changed since you last used it.",
                "startingOver": "You'll be starting over.",
                "by": "by",
                "showMore": "Show more",
                "showLess": "Show less",
                "subLevel": "Sublevel",
                "confirmDialogHeader": "Confirm action",
                "confirmDialogBody": "Please confirm that you wish to proceed. This action is not reversible.",
                "cancelLabel": "Cancel",
                "confirmLabel": "Confirm",
                "licenseU": "Undisclosed",
                "licenseCCBY": "Attribution (CC BY)",
                "licenseCCBYSA": "Attribution-ShareAlike (CC BY-SA)",
                "licenseCCBYND": "Attribution-NoDerivs (CC BY-ND)",
                "licenseCCBYNC": "Attribution-NonCommercial (CC BY-NC)",
                "licenseCCBYNCSA": "Attribution-NonCommercial-ShareAlike (CC BY-NC-SA)",
                "licenseCCBYNCND": "Attribution-NonCommercial-NoDerivs (CC BY-NC-ND)",
                "licenseCC40": "4.0 International",
                "licenseCC30": "3.0 Unported",
                "licenseCC25": "2.5 Generic",
                "licenseCC20": "2.0 Generic",
                "licenseCC10": "1.0 Generic",
                "licenseGPL": "General Public License",
                "licenseV3": "Version 3",
                "licenseV2": "Version 2",
                "licenseV1": "Version 1",
                "licensePD": "Public Domain",
                "licenseCC010": "CC0 1.0 Universal (CC0 1.0) Public Domain Dedication",
                "licensePDM": "Public Domain Mark",
                "licenseC": "Copyright",
                "contentType": "Content Type",
                "licenseExtras": "License Extras",
                "changes": "Changelog",
                "contentCopied": "Content is copied to the clipboard",
                "connectionLost": "Connection lost. Results will be stored and sent when you regain connection.",
                "connectionReestablished": "Connection reestablished.",
                "resubmitScores": "Attempting to submit stored results.",
                "offlineDialogHeader": "Your connection to the server was lost",
                "offlineDialogBody": "We were unable to send information about your completion of this task. Please check your internet connection.",
                "offlineDialogRetryMessage": "Retrying in :num....",
                "offlineDialogRetryButtonLabel": "Retry now",
                "offlineSuccessfulSubmit": "Successfully submitted results.",
                "mainTitle": "Sharing <strong>:title<\/strong>",
                "editInfoTitle": "Edit info for <strong>:title<\/strong>",
                "cancel": "Cancel",
                "back": "Back",
                "next": "Next",
                "reviewInfo": "Review info",
                "share": "Share",
                "saveChanges": "Save changes",
                "registerOnHub": "Register on the H5P Hub",
                "updateRegistrationOnHub": "Save account settings",
                "requiredInfo": "Required Info",
                "optionalInfo": "Optional Info",
                "reviewAndShare": "Review & Share",
                "reviewAndSave": "Review & Save",
                "shared": "Shared",
                "currentStep": "Step :step of :total",
                "sharingNote": "All content details can be edited after sharing",
                "licenseDescription": "Select a license for your content",
                "licenseVersion": "License Version",
                "licenseVersionDescription": "Select a license version",
                "disciplineLabel": "Disciplines",
                "disciplineDescription": "You can select multiple disciplines",
                "disciplineLimitReachedMessage": "You can select up to :numDisciplines disciplines",
                "discipline": {
                    "searchPlaceholder": "Type to search for disciplines",
                    "in": "in",
                    "dropdownButton": "Dropdown button"
                },
                "removeChip": "Remove :chip from the list",
                "keywordsPlaceholder": "Add keywords",
                "keywords": "Keywords",
                "keywordsDescription": "You can add multiple keywords separated by commas. Press \"Enter\" or \"Add\" to confirm keywords",
                "altText": "Alt text",
                "reviewMessage": "Please review the info below before you share",
                "subContentWarning": "Sub-content (images, questions etc.) will be shared under :license unless otherwise specified in the authoring tool",
                "disciplines": "Disciplines",
                "shortDescription": "Short description",
                "longDescription": "Long description",
                "icon": "Icon",
                "screenshots": "Screenshots",
                "helpChoosingLicense": "Help me choose a license",
                "shareFailed": "Share failed.",
                "editingFailed": "Editing failed.",
                "shareTryAgain": "Something went wrong, please try to share again.",
                "pleaseWait": "Please wait...",
                "language": "Language",
                "level": "Level",
                "shortDescriptionPlaceholder": "Short description of your content",
                "longDescriptionPlaceholder": "Long description of your content",
                "description": "Description",
                "iconDescription": "640x480px. If not selected content will use category icon",
                "screenshotsDescription": "Add up to five screenshots of your content",
                "submitted": "Submitted!",
                "isNowSubmitted": "Is now submitted to H5P Hub",
                "changeHasBeenSubmitted": "A change has been submited for",
                "contentAvailable": "Your content will normally be available in the Hub within one business day.",
                "contentUpdateSoon": "Your content will update soon",
                "contentLicenseTitle": "Content License Info",
                "licenseDialogDescription": "Click on a specific license to get info about proper usage",
                "publisherFieldTitle": "Publisher",
                "publisherFieldDescription": "This will display as the \"Publisher name\" on shared content",
                "emailAddress": "Email Address",
                "publisherDescription": "Publisher description",
                "publisherDescriptionText": "This will be displayed under \"Publisher info\" on shared content",
                "contactPerson": "Contact Person",
                "phone": "Phone",
                "address": "Address",
                "city": "City",
                "zip": "Zip",
                "country": "Country",
                "logoUploadText": "Organization logo or avatar",
                "acceptTerms": "I accept the <a href=\":url\" target=\"_blank\">terms of use<\/a>",
                "successfullyRegistred": "You have successfully registered an account on the H5P Hub",
                "successfullyRegistredDescription": "Your account details can be changed",
                "successfullyUpdated": "Your H5P Hub account settings have successfully been changed",
                "accountDetailsLinkText": "here",
                "registrationTitle": "H5P Hub Registration",
                "registrationFailed": "An error occurred",
                "registrationFailedDescription": "We were not able to create an account at this point. Something went wrong. Try again later.",
                "maxLength": ":length is the maximum number of characters",
                "keywordExists": "Keyword already exists!",
                "licenseDetails": "License details",
                "remove": "Remove",
                "removeImage": "Remove image",
                "cancelPublishConfirmationDialogTitle": "Cancel sharing",
                "cancelPublishConfirmationDialogDescription": "Are you sure you want to cancel the sharing process?",
                "cancelPublishConfirmationDialogCancelButtonText": "No",
                "cancelPublishConfirmationDialogConfirmButtonText": "Yes",
                "add": "Add",
                "age": "Typical age",
                "ageDescription": "The target audience of this content. Possible input formats separated by commas: \"1,34-45,-50,59-\".",
                "invalidAge": "Invalid input format for Typical age. Possible input formats separated by commas: \"1, 34-45, -50, -59-\".",
                "contactPersonDescription": "H5P will reach out to the contact person in case there are any issues with the content shared by the publisher. The contact person's name or other information will not be published or shared with third parties",
                "emailAddressDescription": "The email address will be used by H5P to reach out to the publisher in case of any issues with the content or in case the publisher needs to recover their account. It will not be published or shared with any third parties",
                "copyrightWarning": "Copyrighted material cannot be shared in the H5P Content Hub. If the content is licensed with a OER friendly license like Creative Commons, please choose the appropriate license. If not this content cannot be shared.",
                "keywordsExits": "Keywords already exists!",
                "someKeywordsExits": "Some of these keywords already exist",
                "width": "width",
                "height": "height"
            }
        },
        "user": {
            "name": "Zheyu Liang",
            "mail": "z.liang@se21.qmul.ac.uk"
        },
        "hubIsEnabled": true,
        "reportingIsEnabled": true,
        "crossorigin": "anonymous",
        "crossoriginRegex": "^https?:\\\/\\\/",
        "crossoriginCacheBuster": null,
        "libraryConfig": null,
        "pluginCacheBuster": "?ver=2022121200",
        "libraryUrl": "https:\/\/qmplus.qmul.ac.uk\/mod\/hvp\/library\/js",
        "core": {
            "styles": ["\/mod\/hvp\/library\/styles\/h5p.css?ver=2022121200", "\/mod\/hvp\/library\/styles\/h5p-confirmation-dialog.css?ver=2022121200", "\/mod\/hvp\/library\/styles\/h5p-core-button.css?ver=2022121200", "\/mod\/hvp\/library\/styles\/h5p-tooltip.css?ver=2022121200"],
            "scripts": ["\/mod\/hvp\/library\/js\/jquery.js?ver=2022121200", "\/mod\/hvp\/library\/js\/h5p.js?ver=2022121200", "\/mod\/hvp\/library\/js\/h5p-event-dispatcher.js?ver=2022121200", "\/mod\/hvp\/library\/js\/h5p-x-api-event.js?ver=2022121200", "\/mod\/hvp\/library\/js\/h5p-x-api.js?ver=2022121200", "\/mod\/hvp\/library\/js\/h5p-content-type.js?ver=2022121200", "\/mod\/hvp\/library\/js\/h5p-confirmation-dialog.js?ver=2022121200", "\/mod\/hvp\/library\/js\/h5p-action-bar.js?ver=2022121200", "\/mod\/hvp\/library\/js\/request-queue.js?ver=2022121200", "\/mod\/hvp\/library\/js\/h5p-tooltip.js?ver=2022121200"]
        },
        "loadedJs": [],
        "loadedCss": [],
        "contents": {
            "cid-2642": {
                "library": "H5P.InteractiveVideo 1.26",
                "jsonContent": "{\"interactiveVideo\":{\"video\":{\"startScreenOptions\":{\"title\":\"EBU5303 MPEG Interactive Video (Part 1)\",\"hideStartTitle\":false},\"textTracks\":{\"videoTrack\":[{\"label\":\"Subtitles\",\"kind\":\"subtitles\",\"srcLang\":\"en\"}]},\"files\":[{\"path\":\"videos\\\/files-5e9cec1f84887.mp4\",\"mime\":\"video\\\/mp4\",\"copyright\":{\"license\":\"U\"}}]},\"assets\":{\"interactions\":[{\"x\":1.5991479739594743,\"y\":2.8474652426668863,\"width\":37.5,\"height\":21.25,\"duration\":{\"from\":170,\"to\":192},\"libraryTitle\":\"Image\",\"action\":{\"library\":\"H5P.Image 1.1\",\"params\":{\"contentName\":\"Image\",\"file\":{\"path\":\"images\\\/file-5e9cee004548e.jpg\",\"mime\":\"image\\\/jpeg\",\"copyright\":{\"license\":\"U\"},\"width\":848,\"height\":636},\"alt\":\"standards\",\"decorative\":false},\"metadata\":{\"contentType\":\"Image\",\"license\":\"U\",\"title\":\"Untitled Image\"},\"subContentId\":\"39e339d7-b942-40e4-871b-8bab1765febf\"},\"visuals\":{\"backgroundColor\":\"rgba(0,0,0,0)\",\"boxShadow\":true},\"pause\":false,\"displayType\":\"poster\",\"buttonOnMobile\":false,\"goto\":{\"url\":{\"protocol\":\"http:\\\/\\\/\"},\"visualize\":false,\"type\":\"\"},\"label\":\"\"},{\"x\":1.5991479739594743,\"y\":17.093733877197334,\"width\":36.875,\"height\":16.875,\"duration\":{\"from\":168,\"to\":168},\"libraryTitle\":\"True\\\/False Question\",\"action\":{\"library\":\"H5P.TrueFalse 1.8\",\"params\":{\"correct\":\"true\",\"behaviour\":{\"enableRetry\":true,\"enableSolutionsButton\":false,\"enableCheckButton\":true,\"confirmCheckDialog\":false,\"confirmRetryDialog\":false,\"autoCheck\":false},\"l10n\":{\"trueText\":\"True\",\"falseText\":\"False\",\"score\":\"You got @score of @total points\",\"checkAnswer\":\"Check\",\"showSolutionButton\":\"Show solution\",\"tryAgain\":\"Retry\",\"wrongAnswerMessage\":\"Wrong answer\",\"correctAnswerMessage\":\"Correct answer\",\"scoreBarLabel\":\"You got :num out of :total points\",\"a11yCheck\":\"Check the answers. The responses will be marked as correct, incorrect, or unanswered.\",\"a11yShowSolution\":\"Show the solution. The task will be marked with its correct solution.\",\"a11yRetry\":\"Retry the task. Reset all responses and start the task over again.\",\"submitAnswer\":\"Submit\"},\"confirmCheck\":{\"header\":\"Finish ?\",\"body\":\"Are you sure you wish to finish ?\",\"cancelLabel\":\"Cancel\",\"confirmLabel\":\"Finish\"},\"confirmRetry\":{\"header\":\"Retry ?\",\"body\":\"Are you sure you wish to retry ?\",\"cancelLabel\":\"Cancel\",\"confirmLabel\":\"Confirm\"},\"question\":\"<p>The Moving Picture Experts Group (MPEG), a working group of ISO\\\/IEC (officially ISO\\\/IEC JTC 1\\\/SC 29\\\/WG 11) has the mission to develop standards for coded representation of digital audio, video, 3D Graphics and other data. Since its establishment in 1988, the group has developed an impressive portfolio of standards and technologies that help industry offer end users a more enjoyable digital media experience.<\\\/p>\\n\",\"media\":{\"disableImageZooming\":false}},\"metadata\":{\"contentType\":\"True\\\/False Question\",\"license\":\"U\",\"title\":\"Untitled True\\\/False Question\"},\"subContentId\":\"c718e544-b65c-4ffd-b8dc-b230240f19c4\"},\"pause\":true,\"displayType\":\"poster\",\"buttonOnMobile\":false,\"adaptivity\":{\"correct\":{\"allowOptOut\":true,\"message\":\"\"},\"wrong\":{\"allowOptOut\":true,\"message\":\"\"},\"requireCompletion\":false},\"label\":\"\"},{\"x\":1.5991479739594743,\"y\":0.28206901721986588,\"width\":37.5625,\"height\":21.875,\"duration\":{\"from\":287,\"to\":287},\"libraryTitle\":\"Fill in the Blanks\",\"action\":{\"library\":\"H5P.Blanks 1.14\",\"params\":{\"text\":\"<p>Fill in the blanks with either MPEG1 or MPEG2, as appropriate.<\\\/p>\\n\",\"overallFeedback\":[{\"from\":0,\"to\":100}],\"showSolutions\":\"Show solution\",\"tryAgain\":\"Retry\",\"checkAnswer\":\"Check\",\"notFilledOut\":\"Please fill in all blanks to view solution\",\"answerIsCorrect\":\"&#039;:ans&#039; is correct\",\"answerIsWrong\":\"&#039;:ans&#039; is wrong\",\"answeredCorrectly\":\"Answered correctly\",\"answeredIncorrectly\":\"Answered incorrectly\",\"solutionLabel\":\"Correct answer:\",\"inputLabel\":\"Blank input @num of @total\",\"inputHasTipLabel\":\"Tip available\",\"tipLabel\":\"Tip\",\"behaviour\":{\"enableRetry\":true,\"enableSolutionsButton\":false,\"enableCheckButton\":true,\"autoCheck\":false,\"caseSensitive\":false,\"showSolutionsRequiresInput\":true,\"separateLines\":false,\"confirmCheckDialog\":false,\"confirmRetryDialog\":false,\"acceptSpellingErrors\":false},\"scoreBarLabel\":\"You got :num out of :total points\",\"confirmCheck\":{\"header\":\"Finish ?\",\"body\":\"Are you sure you wish to finish ?\",\"cancelLabel\":\"Cancel\",\"confirmLabel\":\"Finish\"},\"confirmRetry\":{\"header\":\"Retry ?\",\"body\":\"Are you sure you wish to retry ?\",\"cancelLabel\":\"Cancel\",\"confirmLabel\":\"Confirm\"},\"questions\":[\"<p>*MPEG1\\\/MPEG2* and *MPEG2\\\/MPEG1* are both standards for the generic coding of moving pictures and associated audio information.<br>\\nThe compression standard for moving pictures and sound to be encoded into the bitrate of a Compact Disc (CD),&nbsp;down to 1.5 Megabits per second is *MPEG1*. Various products and applications use this standard, especially the audio format it introduced, the extremely popular MP3.&nbsp;<\\\/p>\\n\\n<p>*MPEG1* might support 4k video but there is no practical way to encode video for higher resolutions. One may consider *MPEG2* as an *MPEG1* that supports higher resolutions and capable of using higher and variable bitrates. However, one can argue that *MPEG1* performs better in lower bitrates than *MPEG2*.<\\\/p>\\n\"],\"media\":{\"disableImageZooming\":false},\"a11yCheck\":\"Check the answers. The responses will be marked as correct, incorrect, or unanswered.\",\"a11yShowSolution\":\"Show the solution. The task will be marked with its correct solution.\",\"a11yRetry\":\"Retry the task. Reset all responses and start the task over again.\",\"a11yCheckingModeHeader\":\"Checking mode\",\"submitAnswer\":\"Submit\"},\"metadata\":{\"contentType\":\"Fill in the Blanks\",\"license\":\"U\",\"title\":\"MPEG1 \\\/ MPEG2 Fill in the Blanks\"},\"subContentId\":\"5fe1f4bc-9baf-41a5-b9fa-229dc2ba46cf\"},\"pause\":true,\"displayType\":\"poster\",\"buttonOnMobile\":false,\"adaptivity\":{\"correct\":{\"allowOptOut\":true,\"message\":\"\"},\"wrong\":{\"allowOptOut\":true,\"message\":\"\"},\"requireCompletion\":false},\"label\":\"\"}],\"endscreens\":[{\"time\":306.94457999999997,\"label\":\"5:06 Submit screen\"}]},\"summary\":{\"task\":{\"library\":\"H5P.Summary 1.10\",\"params\":{\"intro\":\"Choose the correct statement.\",\"summaries\":[{\"subContentId\":\"e2be0755-4190-4ef3-8ea0-1733d99d2216\",\"tip\":\"\"}],\"overallFeedback\":[{\"from\":0,\"to\":100}],\"solvedLabel\":\"Progress:\",\"scoreLabel\":\"Wrong answers:\",\"resultLabel\":\"Your result\",\"labelCorrect\":\"Correct.\",\"labelIncorrect\":\"Incorrect! Please try again.\",\"labelCorrectAnswers\":\"Correct answers.\",\"tipButtonLabel\":\"Show tip\",\"scoreBarLabel\":\"You got :num out of :total points\",\"progressText\":\"Progress :num of :total\",\"alternativeIncorrectLabel\":\"Incorrect\"},\"metadata\":{\"contentType\":\"Summary\",\"license\":\"U\",\"title\":\"Untitled Summary\"},\"subContentId\":\"41bd6d22-bcb3-4157-a3f3-7b52a62b58a0\"},\"displayAt\":3}},\"override\":{\"autoplay\":false,\"loop\":false,\"showBookmarksmenuOnLoad\":false,\"showRewind10\":false,\"deactivateSound\":false,\"startVideoAt\":0,\"showSolutionButton\":\"off\",\"retryButton\":\"on\",\"preventSkippingMode\":\"none\"},\"l10n\":{\"interaction\":\"Interaction\",\"play\":\"Play\",\"pause\":\"Pause\",\"mute\":\"Mute\",\"unmute\":\"Unmute\",\"quality\":\"Video Quality\",\"captions\":\"Captions\",\"close\":\"Close\",\"fullscreen\":\"Fullscreen\",\"exitFullscreen\":\"Exit Fullscreen\",\"summary\":\"Summary\",\"bookmarks\":\"Bookmarks\",\"endscreen\":\"Submit screen\",\"defaultAdaptivitySeekLabel\":\"Continue\",\"continueWithVideo\":\"Continue with video\",\"playbackRate\":\"Playback Rate\",\"rewind10\":\"Rewind 10 Seconds\",\"navDisabled\":\"Navigation is disabled\",\"sndDisabled\":\"Sound is disabled\",\"requiresCompletionWarning\":\"You need to answer all the questions correctly before continuing.\",\"back\":\"Back\",\"hours\":\"Hours\",\"minutes\":\"Minutes\",\"seconds\":\"Seconds\",\"currentTime\":\"Current time:\",\"totalTime\":\"Total time:\",\"singleInteractionAnnouncement\":\"Interaction appeared:\",\"multipleInteractionsAnnouncement\":\"Multiple interactions appeared.\",\"videoPausedAnnouncement\":\"Video is paused\",\"content\":\"Content\",\"answered\":\"@answered answered\",\"endcardTitle\":\"@answered Question(s) answered\",\"endcardInformation\":\"You have answered @answered questions, click below to submit your answers.\",\"endcardInformationNoAnswers\":\"You have not answered any questions.\",\"endcardInformationMustHaveAnswer\":\"You have to answer at least one question before you can submit your answers.\",\"endcardSubmitButton\":\"Submit Answers\",\"endcardSubmitMessage\":\"Your answers have been submitted!\",\"endcardTableRowAnswered\":\"Answered questions\",\"endcardTableRowScore\":\"Score\",\"endcardAnsweredScore\":\"answered\",\"endCardTableRowSummaryWithScore\":\"You got @score out of @total points for the @question that appeared after @minutes minutes and @seconds seconds.\",\"endCardTableRowSummaryWithoutScore\":\"You have answered the @question that appeared after @minutes minutes and @seconds seconds.\",\"endcardInformationOnSubmitButtonDisabled\":\"You have answered @answered questions.\",\"more\":\"More player options\",\"navForwardDisabled\":\"Navigating forward is disabled\",\"videoProgressBar\":\"Video progress\"}}",
                "fullScreen": "1",
                "exportUrl": "https:\/\/qmplus.qmul.ac.uk\/pluginfile.php\/2303371\/mod_hvp\/exports\/ebu5303-mpeg-interactive-video-part-2-2642.h5p",
                "embedCode": "<iframe src=\"https:\/\/qmplus.qmul.ac.uk\/mod\/hvp\/embed.php?id=1355653\" width=\":w\" height=\":h\" frameborder=\"0\" allowfullscreen=\"allowfullscreen\" title=\"EBU5303 MPEG Interactive Video (Part 1)\"><\/iframe>",
                "resizeCode": "<script src=\"https:\/\/qmplus.qmul.ac.uk\/mod\/hvp\/library\/js\/h5p-resizer.js\" charset=\"UTF-8\"><\/script>",
                "title": "EBU5303 MPEG Interactive Video (Part 1)",
                "displayOptions": {
                    "frame": true,
                    "export": true,
                    "embed": true,
                    "copyright": true,
                    "icon": true,
                    "copy": false
                },
                "url": "https:\/\/qmplus.qmul.ac.uk\/mod\/hvp\/view.php?id=1355653",
                "contentUrl": "https:\/\/qmplus.qmul.ac.uk\/pluginfile.php\/2303371\/mod_hvp\/content\/2642",
                "metadata": {
                    "title": "EBU5303 MPEG Interactive Video (Part 1)",
                    "license": "U",
                    "defaultLanguage": "en"
                },
                "contentUserData": [{
                    "state": "{}"
                }],
                "scripts": ["https:\/\/qmplus.qmul.ac.uk\/pluginfile.php\/1\/mod_hvp\/cachedassets\/9afbaf625a4c0cd0469866c10d6434a7cf223608.js"],
                "styles": ["https:\/\/qmplus.qmul.ac.uk\/pluginfile.php\/1\/mod_hvp\/cachedassets\/9afbaf625a4c0cd0469866c10d6434a7cf223608.css"]
            }
        }
    };
    //]]>
</script>